### ISSUE TITLE
THE WEBSITE IS DOWN

### ISSUE THREAD

**Issue by FellFromTheSky** [OpenLiveWriter/OpenLiveWriter.Github.io#128]
Hello, sorry for yelling but, it seems that the website is down since a while now.
Will it go live any soon?

**Comment by brianlagunas** [comment]
Try this instead: https://openlivewriter.com/

**Comment by FellFromTheSky** [comment]
Oh ok thanks, but even this one was down for a while, I think.
Now it's not anymore.

**Comment by cloudlene** [comment]
Thanks!  Didn’t know Windows Live Writer is now Open Live Writer!

**Comment by FellFromTheSky** [comment]
...
Windows Live Writer is now Open Live Writer
...
Not really, it's like saying that Microsoft Silverlight is OpenSilver.
One is a closed source software when the other one is a free open source software.
Then like Microsoft Silverlight and OpenSilver, they should maybe not have the same features.
So yeah, just try the one that is better for you, but never download something that is not from official sources, like GitHub website or Microsoft one for example.
