### ISSUE TITLE
Add page to document how to set up FTP Site

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#17]
This page will help resolve [Issue 179 FTP help page is missing when you click on "How do I configure FTP site?] https://github.com/OpenLiveWriter/OpenLiveWriter/issues/179 and provide further user documentation.

The OpenLiveWriter link is currently: http://openlivewriter.org/WriterRedirect/WriterFTPHelpV3?Version=0.0&Build=5.0&Market=en-US

The LiveWriter page exists at http://windows.microsoft.com/en-US/windows-live/writer-ftp-server-images-photos-ui

Question: Do we want to use the existing link (Not very description), or create an entirely new page, and link to the new page.

I vote for the software change.

**Comment by RobStand** [comment]
@kathweaver I think we should create an entirely new page so we don't depend on WLW information. Feel free to create one, if you want. We can include it in the website doco and link to it from OLW.

**Comment by kathweaver** [comment]
Have a pull request #27 for that

**Comment by kathweaver** [comment]
Working on an entirely new page.

**Comment by RobStand** [comment]
PR accepted. This appears to be completed.

**Comment by kathweaver** [comment]
Thank you!
