### ISSUE TITLE
Need site navigation

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter.Github.io#20]
We really need some basic navigation in the site.  Here are the things I can think of that we'd like to have on the site if we can figure out where to link it all:

 - Front page (Download, elevator pitch and screenshots)
 - News / Blog (it's very ironic that the key offline tool for bloggers doesn't have a blog bloggers can subscribe to)
 - Tutorial
   -  How to get started with the various blog services we support
   -  Inserting images (with accessibility info), inserting video etc
   -  Power features and other options etc
 - Plugin Gallery
 - Getting Involved with the community
    - Bug reports
    - Feature suggestions
    - Developing
    - Localization / Translations
 - Discussions / Forums / Getting Help
 - About the project, some history etc

If anyone feels like having a go at the basic layout of the site to give us a structure for our site navigation then be my guest. I think that would then unblock things like #15 and much more.

**Comment by kathweaver** [comment]
We have a redirect to it already:

  <feature name="Writer Blog" enabled="false"> 
             <parameter name="Glink" value="http://openlivewriter.org/WriterRedirect/WriterBlog" />

**Comment by kathweaver** [comment]
<feature name="Writer Blog" enabled="false"> 
            <parameter name="Glink" value="http://openlivewriter.org/WriterRedirect/WriterBlog" />

**Comment by RobDolinMS** [comment]
I reserved http://OpenLiveWriter.WordPress.com/ a while ago if we want to have a blog.  
It might make sense to have a "in the news" section with links to coverage of the launch (and similar)

**Comment by kathweaver** [comment]
Invite me via Wordpress, and I'll work on it.

**Comment by kathweaver** [comment]
I've done a pull request for this.

**Comment by hashhar** [comment]
We do have the Front Page at `openlivewriter.org`.  
The blog may be created at `/_posts/blog` since we can use the amazing Jekyll.  
For the tutorial I was thinking of using the same set of documentation in the `OpenLiveWriter` repo (the markdown files).
All of the remaining content would have to be written since it doesn't already exist. I am working on adding a navbar.

**Comment by kathweaver** [comment]
I can certainly help with documentation but I am tied up for the next days.  I'm close to finishing the test plans, and want to get to them next.

**Comment by kathweaver** [comment]
Sounds good, but does that mean blogging in .md?  Or can we do it with livewriter and html?

**Comment by hashhar** [comment]
You can do it either way. In the end GitHub itself converts the markdown to html for viewing. The only advantage markdown provides it that it can be reused in the main OLW repo also and not just the website (and looks a **little** more clean to **me**)
