### ISSUE TITLE
Redirect Question

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#25]
In OpenLiveWriter.Github.io / getting-started / index.html 
we have 

  - /WriterRedirect/WriterHelpV3/ 
  - /WriterRedirect/LearnMore/ 

Don't we need to create those redirects?  I can do it, but wasn't sure how this works

**Comment by rebornix** [comment]
These two configs are actually used by `jekyll-redirect-from` gem which used by GitHub page for backwards compatibility. It will redirect all requests to these two urls to `/gettting-started/` automatically. So if we don't want to create real page for these two links, we can keep the redirection.

**Comment by kathweaver** [comment]
Thanks, so I need look at Jekyll-redirect-from ?

**Comment by rebornix** [comment]
@kathweaver that's not necessary, just leave it there, if you meet any issues related to redirect, leave it to me.
