### ISSUE TITLE
"Learn More About Live Writer" is opening FTP setup, should open Getting Started

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#34]
Clicking on 
<img width="331" alt="2016-01-16_20-09-29" src="https://cloud.githubusercontent.com/assets/7053084/12375562/8eed0700-bc8d-11e5-895c-85afe5d478d7.png">
sends me to:
<img width="958" alt="2016-01-16_20-13-51" src="https://cloud.githubusercontent.com/assets/7053084/12375567/c21b466e-bc8d-11e5-91fe-a4cca03b1ad4.png">

**Comment by hashhar** [comment]
I'll check that and try sending a fix.

**Comment by kathweaver** [comment]
I figured it out and have a pull request waiting.

**Comment by hashhar** [comment]
Oh. Great. :D :+1:

**Comment by kathweaver** [comment]
yes, I have been playing with Jekyll

**Comment by kathweaver** [comment]
pull request #35 should fix this

**Comment by kathweaver** [comment]
Reopened as the #35 hasn't been merged.

**Comment by kathweaver** [comment]
Thanks RobStand!  I was quite embarrassed that my lack of knowledge of Jekyl caused a bug!  So I've been learning it.

**Comment by miwebguy** [comment]
http://openlivewriter.org/WriterRedirect/LearnMore/%7B
