### ISSUE TITLE
Reduce vertical space in navigation

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter.Github.io#48]
If anyone gets chance to do some CSS hackery, I would love for us to try and reduce the vertical space that the addition of navigation has added.  I was thinking something like below, but completely open to other ideas.

![image](https://cloud.githubusercontent.com/assets/856858/12951048/676e04b6-d008-11e5-9318-ffecba0401d9.png)

**Comment by hashhar** [comment]
@martinwoodward On it now. I could make it exactly like you pointed out, looks great. Will submit a PR sometime tomorrow.

**Comment by martinwoodward** [comment]
Wow - awesome!  Thanks @hashhar. I was going to have a play to see what it looks like on pages that have the download button set to false  We might need to have the tab be grey in color in those instances so it blends in - but I couldn't think of an elegant way to do that off the top of my head yet. Also haven't figured out what the on-hover behavior should be but we could just play with some options live in browser once you have the nav moved down?

Anyway, have a play and see what you can come up with - don't take my Photoshop doodle as a well thought out design by any means ;-)

**Comment by kathweaver** [comment]
Actually I'm on it too!  

I've got this:

**Comment by martinwoodward** [comment]
:sparkling_heart: - @hashhar, would you mind taking a look at PR #50 with @kathweaver and let me know when you are both happy with it?  Thanks folks - I LOVE the Live Writer community!  I mostly wrote the issue just as a TODO for myself as well as get some feedback on the idea and I turn around and it's getting built.  You rock!

**Comment by kathweaver** [comment]
Thanks!  I like the way it looks -- I messed with the colors a bit but like it this way the best.

**Comment by kathweaver** [comment]
I like @hannakim123 latest #51 and I closed mine
