### ISSUE TITLE
Fix nav in 404 page

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter.Github.io#53]
The cool new nav has introduced an error in the 404 page

Go to something like http://openlivewriter.org/fkjhfrjkhfkhjfrhrkjhme to repo

![image](https://cloud.githubusercontent.com/assets/856858/12982977/28ede0a8-d0df-11e5-9de8-3d23b5bbb678.png)

**Comment by kathweaver** [comment]
Okay, I don't understand what's wrong.

**Comment by hashhar** [comment]
That white space below the nav. Okay. Lemme see.
