### ISSUE TITLE
Download is not displayed

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#59]
Anytime ### Downloads is in a new post, it is ignored.  Or an icon shows up, but not near the files, not sure which.

**Comment by hashhar** [comment]
Ah, I guess #57 will fix it. Any heading(other things may be affected too) that has the content `Downloads` goes somewhere invisible or messes something else up.

**Comment by kathweaver** [comment]
Fixed with #57  Thanks!
