### ISSUE TITLE
White gap above header options on 404 page

### ISSUE THREAD

**Issue by ScottIsAFool** [OpenLiveWriter/OpenLiveWriter.Github.io#62]
Screenshot is fairly self explanatory :) (this was in chrome).

![image](https://cloud.githubusercontent.com/assets/1658896/13034728/f2d3811e-d334-11e5-9d8f-1e74d0e4a785.png)

**Comment by kathweaver** [comment]
Assign to @hashhar please

**Comment by ScottIsAFool** [comment]
I can't, he doesn't appear in the list of assignees.

**Comment by hashhar** [comment]
#55 fixes it. Dupe of #53

**Comment by ScottIsAFool** [comment]
Oops, *slaps wrist for not checking*

**Comment by kathweaver** [comment]
Well, mentioning him in my comment did it.

**Comment by hashhar** [comment]
@ScottIsAFool Only the people who have write access on a repository can be made assignees.
