### ISSUE TITLE
Tutorial Titles are inconsistent

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter.Github.io#75]
@hashhar The titles you modified aren't showing up in the tutorials, and they are inconsistent.

For example:

http://openlivewriter.org/tutorials/watermarkPictures.html  is showing up correctly (but I will remove the <h3>

http://openlivewriter.org/tutorials/addBlogAccts/ is not showing up correctly.

Please tell me what the correct syntax and let ME fix it.  That will help with future tutorials.

**Comment by hashhar** [comment]
It's actually not so much about the format than about the `layout: post` or `layout: page` at the top of the pages. `page` wouldn't show the title but `post` will.

**Comment by kathweaver** [comment]
Thanks -- figured by running Jekyll and comparing everything.

Please don't alter the tutorial files again.  Thanks!

**Comment by RobStand** [comment]
Fixed with #76
